export const paths = {
  auth: 'auth',
  cache: 'cache',
  fake: 'fake',
  error: 'error',
  profiler: 'profiler',
  notify: 'notify',
  header: 'header',
  convert: 'convert',
  loader: 'loader',
  https: 'https',
};

export const routeNames = {
  login: 'Login',
  home: 'Inicio',
};



export const ListDepartment: any = [
  { IdDepartament: '1', Description: 'BE' },
  { IdDepartament: '2', Description: 'CH' },
  { IdDepartament: '3', Description: 'CB' },
  { IdDepartament: '4', Description: 'LP' },
  { IdDepartament: '5', Description: 'OR' },
  { IdDepartament: '6', Description: 'PD' },
  { IdDepartament: '7', Description: 'PT' },
  { IdDepartament: '8', Description: 'SC' },
  { IdDepartament: '9', Description: 'TJ' },
];

export const OptionSidenavClient: any = [
  { Icon: 'note_alt', Route: 'reserva', Label: 'Reservas' },
];

export const OptionSidenavAdmin: any = [
  { Icon: 'group', Route: 'usuario', Label: 'Usuarios' },
  { Icon: 'face_2', Route: 'beneficiario', Label: 'Beneficiarios' },
  { Icon: 'video_camera_front', Route: 'capacitacion', Label: 'Capacitaciones' },
];

export const ListCountries = [
  { Id: 'BD', Description: 'Bangladesh' },
  { Id: 'BE', Description: 'Belgium' },
  { Id: 'BF', Description: 'Burkina Faso' },
  { Id: 'BG', Description: 'Bulgaria' },
  { Id: 'BA', Description: 'Bosnia and Herzegovina' },
  { Id: 'BB', Description: 'Barbados' },
  { Id: 'WF', Description: 'Wallis and Futuna' },
  { Id: 'BL', Description: 'Saint Barthelemy' },
  { Id: 'BM', Description: 'Bermuda' },
  { Id: 'BO', Description: 'Bolivia' },
  { Id: 'BH', Description: 'Bahrain' },
  { Id: 'BI', Description: 'Burundi' },
  { Id: 'BJ', Description: 'Benin' },
  { Id: 'BT', Description: 'Bhutan' },
  { Id: 'JM', Description: 'Jamaica' },
  { Id: 'BV', Description: 'Bouvet Island' },
  { Id: 'BW', Description: 'Botswana' },
  { Id: 'WS', Description: 'Samoa' },
  { Id: 'BQ', Description: 'Bonaire, Saint Eustatius and Saba ' },
  { Id: 'BR', Description: 'Brazil' },
  { Id: 'BS', Description: 'Bahamas' },
  { Id: 'JE', Description: 'Jersey' },
  { Id: 'BY', Description: 'Belarus' },
  { Id: 'BZ', Description: 'Belize' },
  { Id: 'RU', Description: 'Russia' },
  { Id: 'RW', Description: 'Rwanda' },
  { Id: 'RS', Description: 'Serbia' },
  { Id: 'TL', Description: 'East Timor' },
  { Id: 'RE', Description: 'Reunion' },
  { Id: 'TM', Description: 'Turkmenistan' },
  { Id: 'TJ', Description: 'Tajikistan' },
  { Id: 'RO', Description: 'Romania' },
  { Id: 'TK', Description: 'Tokelau' },
  { Id: 'GW', Description: 'Guinea-Bissau' },
  { Id: 'GU', Description: 'Guam' },
  { Id: 'GT', Description: 'Guatemala' },
  { Id: 'GS', Description: 'South Georgia and the South Sandwich Islands' },
  { Id: 'GR', Description: 'Greece' },
  { Id: 'GQ', Description: 'Equatorial Guinea' },
  { Id: 'GP', Description: 'Guadeloupe' },
  { Id: 'JP', Description: 'Japan' },
  { Id: 'GY', Description: 'Guyana' },
  { Id: 'GG', Description: 'Guernsey' },
  { Id: 'GF', Description: 'French Guiana' },
  { Id: 'GE', Description: 'Georgia' },
  { Id: 'GD', Description: 'Grenada' },
  { Id: 'GB', Description: 'United Kingdom' },
  { Id: 'GA', Description: 'Gabon' },
  { Id: 'SV', Description: 'El Salvador' },
  { Id: 'GN', Description: 'Guinea' },
  { Id: 'GM', Description: 'Gambia' },
  { Id: 'GL', Description: 'Greenland' },
  { Id: 'GI', Description: 'Gibraltar' },
  { Id: 'GH', Description: 'Ghana' },
  { Id: 'OM', Description: 'Oman' },
  { Id: 'TN', Description: 'Tunisia' },
  { Id: 'JO', Description: 'Jordan' },
  { Id: 'HR', Description: 'Croatia' },
  { Id: 'HT', Description: 'Haiti' },
  { Id: 'HU', Description: 'Hungary' },
  { Id: 'HK', Description: 'Hong Kong' },
  { Id: 'HN', Description: 'Honduras' },
  { Id: 'HM', Description: 'Heard Island and McDonald Islands' },
  { Id: 'VE', Description: 'Venezuela' },
  { Id: 'PR', Description: 'Puerto Rico' },
  { Id: 'PS', Description: 'Palestinian Territory' },
  { Id: 'PW', Description: 'Palau' },
  { Id: 'PT', Description: 'Portugal' },
  { Id: 'SJ', Description: 'Svalbard and Jan Mayen' },
  { Id: 'PY', Description: 'Paraguay' },
  { Id: 'IQ', Description: 'Iraq' },
  { Id: 'PA', Description: 'Panama' },
  { Id: 'PF', Description: 'French Polynesia' },
  { Id: 'PG', Description: 'Papua New Guinea' },
  { Id: 'PE', Description: 'Peru' },
  { Id: 'PK', Description: 'Pakistan' },
  { Id: 'PH', Description: 'Philippines' },
  { Id: 'PN', Description: 'Pitcairn' },
  { Id: 'PL', Description: 'Poland' },
  { Id: 'PM', Description: 'Saint Pierre and Miquelon' },
  { Id: 'ZM', Description: 'Zambia' },
  { Id: 'EH', Description: 'Western Sahara' },
  { Id: 'EE', Description: 'Estonia' },
  { Id: 'EG', Description: 'Egypt' },
  { Id: 'ZA', Description: 'South Africa' },
  { Id: 'EC', Description: 'Ecuador' },
  { Id: 'IT', Description: 'Italy' },
  { Id: 'VN', Description: 'Vietnam' },
  { Id: 'SB', Description: 'Solomon Islands' },
  { Id: 'ET', Description: 'Ethiopia' },
  { Id: 'SO', Description: 'Somalia' },
  { Id: 'ZW', Description: 'Zimbabwe' },
  { Id: 'SA', Description: 'Saudi Arabia' },
  { Id: 'ES', Description: 'Spain' },
  { Id: 'ER', Description: 'Eritrea' },
  { Id: 'ME', Description: 'Montenegro' },
  { Id: 'MD', Description: 'Moldova' },
  { Id: 'MG', Description: 'Madagascar' },
  { Id: 'MF', Description: 'Saint Martin' },
  { Id: 'MA', Description: 'Morocco' },
  { Id: 'MC', Description: 'Monaco' },
  { Id: 'UZ', Description: 'Uzbekistan' },
  { Id: 'MM', Description: 'Myanmar' },
  { Id: 'ML', Description: 'Mali' },
  { Id: 'MO', Description: 'Macao' },
  { Id: 'MN', Description: 'Mongolia' },
  { Id: 'MH', Description: 'Marshall Islands' },
  { Id: 'MK', Description: 'Macedonia' },
  { Id: 'MU', Description: 'Mauritius' },
  { Id: 'MT', Description: 'Malta' },
  { Id: 'MW', Description: 'Malawi' },
  { Id: 'MV', Description: 'Maldives' },
  { Id: 'MQ', Description: 'Martinique' },
  { Id: 'MP', Description: 'Northern Mariana Islands' },
  { Id: 'MS', Description: 'Montserrat' },
  { Id: 'MR', Description: 'Mauritania' },
  { Id: 'IM', Description: 'Isle of Man' },
  { Id: 'UG', Description: 'Uganda' },
  { Id: 'TZ', Description: 'Tanzania' },
  { Id: 'MY', Description: 'Malaysia' },
  { Id: 'MX', Description: 'Mexico' },
  { Id: 'IL', Description: 'Israel' },
  { Id: 'FR', Description: 'France' },
  { Id: 'IO', Description: 'British Indian Ocean Territory' },
  { Id: 'SH', Description: 'Saint Helena' },
  { Id: 'FI', Description: 'Finland' },
  { Id: 'FJ', Description: 'Fiji' },
  { Id: 'FK', Description: 'Falkland Islands' },
  { Id: 'FM', Description: 'Micronesia' },
  { Id: 'FO', Description: 'Faroe Islands' },
  { Id: 'NI', Description: 'Nicaragua' },
  { Id: 'NL', Description: 'Netherlands' },
  { Id: 'NO', Description: 'Norway' },
  { Id: 'NA', Description: 'Namibia' },
  { Id: 'VU', Description: 'Vanuatu' },
  { Id: 'NC', Description: 'New Caledonia' },
  { Id: 'NE', Description: 'Niger' },
  { Id: 'NF', Description: 'Norfolk Island' },
  { Id: 'NG', Description: 'Nigeria' },
  { Id: 'NZ', Description: 'New Zealand' },
  { Id: 'NP', Description: 'Nepal' },
  { Id: 'NR', Description: 'Nauru' },
  { Id: 'NU', Description: 'Niue' },
  { Id: 'CK', Description: 'Cook Islands' },
  { Id: 'XK', Description: 'Kosovo' },
  { Id: 'CI', Description: 'Ivory Coast' },
  { Id: 'CH', Description: 'Switzerland' },
  { Id: 'CO', Description: 'Colombia' },
  { Id: 'CN', Description: 'China' },
  { Id: 'CM', Description: 'Cameroon' },
  { Id: 'CL', Description: 'Chile' },
  { Id: 'CC', Description: 'Cocos Islands' },
  { Id: 'CA', Description: 'Canada' },
  { Id: 'CG', Description: 'Republic of the Congo' },
  { Id: 'CF', Description: 'Central African Republic' },
  { Id: 'CD', Description: 'Democratic Republic of the Congo' },
  { Id: 'CZ', Description: 'Czech Republic' },
  { Id: 'CY', Description: 'Cyprus' },
  { Id: 'CX', Description: 'Christmas Island' },
  { Id: 'CR', Description: 'Costa Rica' },
  { Id: 'CW', Description: 'Curacao' },
  { Id: 'CV', Description: 'Cape Verde' },
  { Id: 'CU', Description: 'Cuba' },
  { Id: 'SZ', Description: 'Swaziland' },
  { Id: 'SY', Description: 'Syria' },
  { Id: 'SX', Description: 'Sint Maarten' },
  { Id: 'KG', Description: 'Kyrgyzstan' },
  { Id: 'KE', Description: 'Kenya' },
  { Id: 'SS', Description: 'South Sudan' },
  { Id: 'SR', Description: 'Suriname' },
  { Id: 'KI', Description: 'Kiribati' },
  { Id: 'KH', Description: 'Cambodia' },
  { Id: 'KN', Description: 'Saint Kitts and Nevis' },
  { Id: 'KM', Description: 'Comoros' },
  { Id: 'ST', Description: 'Sao Tome and Principe' },
  { Id: 'SK', Description: 'Slovakia' },
  { Id: 'KR', Description: 'South Korea' },
  { Id: 'SI', Description: 'Slovenia' },
  { Id: 'KP', Description: 'North Korea' },
  { Id: 'KW', Description: 'Kuwait' },
  { Id: 'SN', Description: 'Senegal' },
  { Id: 'SM', Description: 'San Marino' },
  { Id: 'SL', Description: 'Sierra Leone' },
  { Id: 'SC', Description: 'Seychelles' },
  { Id: 'KZ', Description: 'Kazakhstan' },
  { Id: 'KY', Description: 'Cayman Islands' },
  { Id: 'SG', Description: 'Singapore' },
  { Id: 'SE', Description: 'Sweden' },
  { Id: 'SD', Description: 'Sudan' },
  { Id: 'DO', Description: 'Dominican Republic' },
  { Id: 'DM', Description: 'Dominica' },
  { Id: 'DJ', Description: 'Djibouti' },
  { Id: 'DK', Description: 'Denmark' },
  { Id: 'VG', Description: 'British Virgin Islands' },
  { Id: 'DE', Description: 'Germany' },
  { Id: 'YE', Description: 'Yemen' },
  { Id: 'DZ', Description: 'Algeria' },
  { Id: 'US', Description: 'United States' },
  { Id: 'UY', Description: 'Uruguay' },
  { Id: 'YT', Description: 'Mayotte' },
  { Id: 'UM', Description: 'United States Minor Outlying Islands' },
  { Id: 'LB', Description: 'Lebanon' },
  { Id: 'LC', Description: 'Saint Lucia' },
  { Id: 'LA', Description: 'Laos' },
  { Id: 'TV', Description: 'Tuvalu' },
  { Id: 'TW', Description: 'Taiwan' },
  { Id: 'TT', Description: 'Trinidad and Tobago' },
  { Id: 'TR', Description: 'Turkey' },
  { Id: 'LK', Description: 'Sri Lanka' },
  { Id: 'LI', Description: 'Liechtenstein' },
  { Id: 'LV', Description: 'Latvia' },
  { Id: 'TO', Description: 'Tonga' },
  { Id: 'LT', Description: 'Lithuania' },
  { Id: 'LU', Description: 'Luxembourg' },
  { Id: 'LR', Description: 'Liberia' },
  { Id: 'LS', Description: 'Lesotho' },
  { Id: 'TH', Description: 'Thailand' },
  { Id: 'TF', Description: 'French Southern Territories' },
  { Id: 'TG', Description: 'Togo' },
  { Id: 'TD', Description: 'Chad' },
  { Id: 'TC', Description: 'Turks and Caicos Islands' },
  { Id: 'LY', Description: 'Libya' },
  { Id: 'VA', Description: 'Vatican' },
  { Id: 'VC', Description: 'Saint Vincent and the Grenadines' },
  { Id: 'AE', Description: 'United Arab Emirates' },
  { Id: 'AD', Description: 'Andorra' },
  { Id: 'AG', Description: 'Antigua and Barbuda' },
  { Id: 'AF', Description: 'Afghanistan' },
  { Id: 'AI', Description: 'Anguilla' },
  { Id: 'VI', Description: 'U.S. Virgin Islands' },
  { Id: 'IS', Description: 'Iceland' },
  { Id: 'IR', Description: 'Iran' },
  { Id: 'AM', Description: 'Armenia' },
  { Id: 'AL', Description: 'Albania' },
  { Id: 'AO', Description: 'Angola' },
  { Id: 'AQ', Description: 'Antarctica' },
  { Id: 'AS', Description: 'American Samoa' },
  { Id: 'AR', Description: 'Argentina' },
  { Id: 'AU', Description: 'Australia' },
  { Id: 'AT', Description: 'Austria' },
  { Id: 'AW', Description: 'Aruba' },
  { Id: 'IN', Description: 'India' },
  { Id: 'AX', Description: 'Aland Islands' },
  { Id: 'AZ', Description: 'Azerbaijan' },
  { Id: 'IE', Description: 'Ireland' },
  { Id: 'ID', Description: 'Indonesia' },
  { Id: 'UA', Description: 'Ukraine' },
  { Id: 'QA', Description: 'Qatar' },
  { Id: 'MZ', Description: 'Mozambique' },
];

